import Head from "next/head";
import styles from '../../styles/detail.module.scss'
import Pagination from "../../components/Pagination/Pagination";
import Image from "next/image";
import Link from "next/link";
import { isArray } from "../../utils";
import { useRouter } from "next/router";
import Header from "../../components/Header/Header";
import Layout from "../../components/Layout/Layout";
const options = Array(3).fill({
  name : "Dưỡng trắng",
})
const renderOption = function (options) {
  return (
      options.map((option,index) => (
        <div className={styles.option_tag}>{option.name}</div>
          )
      )
  );
}
const choices = Array(3).fill({
  text: "Nước hoa Atelier Cologne Iris Rebelle Cologne Absolue Pure Perfume",

})
const renderChoices = function (choices) {
  return (
      choices.map((choice,index) => (
        <div>
                <Link className={styles.url} href="#">
                  <Image className={styles.img_makeup} src={require("../../public/rectangle 559.png")} alt="" />
                  <p>
                    {choice.text}
                  </p>
                  <Image className={styles.img_vector} src={require("../../public/vector.png")} alt="" />
                </Link>
              </div>
          )
      )
  );
}
export default function DetailMagazine() {
  const router = useRouter();
  const query = router.query;
  const slug = query.slug;
  console.log("slug", slug);

  return (
    <>
      <Head>
        <title>Magazine-detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.detail}>
        <Header />
        <Layout>
          <div>
            <Image className={styles.img_banner} src={require("../../public/group 3065.png")} alt="" />
          </div>
          <div className={styles.container}>
            <div className={styles.block_small}>
              <Image className={styles.img_banner_small} src={require("../../public/content.png")} alt="" />
            </div>
            <h1 className={styles.title_main}>
              3 tiêu chuẩn lựa chọn tẩy trang cho da nhạy cảm hỗn hợp
            </h1>
            <div className={styles.list_info}>
              <div className={styles.info}>
                <Image className={styles.calendar_icon} src={require("../../public/calendar.png")} alt="" />
                <p>Jul 08 2018</p>
              </div>
              <div className={styles.info}>
                <Image className={styles.eye_icon} src={require("../../public/eye.png")} alt="" />
                <p>Jul 08 2018</p>
              </div>
            </div>
            <div className={styles.section_1}>
              <div className={styles.line}></div>
              <p>
                Nóng, rát, nổi mụn, da nổi mẩn đỏ hoặc ngứa sưng là tình trạng
                thường thấy của da nhạy cảm khi sử dụng các sản phẩm tẩy trang
                không phù hợp. Vậy làm thế nào để lựa chọn đúng sản phẩm tẩy
                trang sạch hiệu quả nhưng vẫn nhẹ nhàng với làn da? Ghi nhớ ngay
                3 tiêu chí dưới đây, đảm bảo làn da sẽ không còn mẩn đỏ vì tẩy
                trang nữa.
              </p>
            </div>
            <div>
              <h3 className={styles.title_small}>
                1. Tránh xa các thành phần gây kích ứng
              </h3>
              <p className={styles.content_small}>
                Đối với làn da nhạy cảm, điều quan trọng nhất chính là hãy luôn
                quan tâm đến thành phần trong sản phẩm tẩy trang để tránh bị
                kích ứng. Bạn sẽ khá bất ngờ khi nhìn thấy một số thành phần phổ
                biến như alcohol (cồn), paraben (chất bảo quản), mineral oil
                (dầu khoáng), fragrance (hương liệu),... sẽ có thể là nguyên
                nhân gây ra tình trạng kích ứng, mẩn đỏ cho làn da nhạy cảm. Vì
                thế, hãy kiểm tra thật kỹ bảng thành phần và loại ngay các sản
                phẩm chứa những chất trên để “đảm bảo an toàn” cho làn da nhạy
                cảm.
              </p>
              <Image
                className={styles.img_banner_makeup}
                src={require("../../public/image 33.png").src}
                alt=""
              />
            </div>
            <div className={styles.list_url}>
              {renderChoices(choices)}
            </div>
            <div>
              <h3 className={styles.title_small}>
                2. Tránh xa các thành phần gây kích ứng
              </h3>
              <p className={styles.content_small}>
                Đối với làn da nhạy cảm, điều quan trọng nhất chính là hãy luôn
                quan tâm đến thành phần trong sản phẩm tẩy trang để tránh bị
                kích ứng. Bạn sẽ khá bất ngờ khi nhìn thấy một số thành phần phổ
                biến như alcohol (cồn), paraben (chất bảo quản), mineral oil
                (dầu khoáng), fragrance (hương liệu),... sẽ có thể là nguyên
                nhân gây ra tình trạng kích ứng, mẩn đỏ cho làn da nhạy cảm. Vì
                thế, hãy kiểm tra thật kỹ bảng thành phần và loại ngay các sản
                phẩm chứa những chất trên để “đảm bảo an toàn” cho làn da nhạy
                cảm.
              </p>
              <Image
                className={styles.img_banner_makeup}
                src={require("../../public/image 33.png").src}
                alt=""
              />
            </div>
            <p className={styles.tag}>TAG</p>
            <div className={styles.list_tag}>
              {renderOption(options)}
            </div>
            <div className={styles.button}>
              <button className={styles.share_button}>
                SHARE THIS
                <Image 
                  src={require("../../public/path.png")}
                  className={styles.icon_share}
                />
              </button>
              <div className={styles.community}>
                <button className={styles.fb_button}>
                  <Image 
                    src={require("../../public/fb.png")}
                    className={styles.icon_fb}
                  />
                  Chia sẻ
                </button>
                <button className={styles.like_button}>
                  <Image 
                    src={require("../../public/group 2487.png")}
                    className={styles.icon_like}
                  />
                  Chia sẻ
                </button>
              </div>
            </div>
            <div className={styles.stt_fb}>
              <Image
                src={require("../../public/Mask Group.png")}
              />
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
