import Head from "next/head";
import Pagination from "../../components/Pagination/Pagination";
import Image from "next/image";
import Link from "next/link";
import { isArray } from "../../utils";
import { useRouter } from "next/router";
// import  '../styles/magazine.scss'
import bigbanner from "../../public/group 3065.png";
import calendar from "../../public/calendar.png";
import eye from "../../public/eye.png";
import vector from "../../public/vector.png";
import makeup from "../../public/rectangle 559.png";
import bannermakeup from "../../public/image 33.png";
import smallbanner from "../../public/content.png";
import Header from "../../components/Header/Header";
import Layout from "../../components/Layout/Layout";

export default function DetailMagazine() {
  const router = useRouter();
  const query = router.query;
  const slug = query.slug;
  console.log("slug", slug);

  return (
    <>
      <Head>
        <title>Magazine-detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="detail">
        <Header />
        <Layout>
          <div>
            <img className="img-banner" src={bigbanner.src} alt="" />
          </div>
          <div className="container">
            <div className="block-small">
              <img className="img-banner-small" src={smallbanner.src} alt="" />
            </div>
            <h1 className="title-main">
              3 tiêu chuẩn lựa chọn tẩy trang cho da nhạy cảm hỗn hợp
            </h1>
            <div className="list-info">
              <div className="info">
                <img className="calendar-icon" src={calendar.src} alt="" />
                <p>Jul 08 2018</p>
              </div>
              <div className="info">
                <img className="eye-icon" src={eye.src} alt="" />
                <p>Jul 08 2018</p>
              </div>
            </div>
            <div className="section-1">
              <div className="line"></div>
              <p>
                Nóng, rát, nổi mụn, da nổi mẩn đỏ hoặc ngứa sưng là tình trạng
                thường thấy của da nhạy cảm khi sử dụng các sản phẩm tẩy trang
                không phù hợp. Vậy làm thế nào để lựa chọn đúng sản phẩm tẩy
                trang sạch hiệu quả nhưng vẫn nhẹ nhàng với làn da? Ghi nhớ ngay
                3 tiêu chí dưới đây, đảm bảo làn da sẽ không còn mẩn đỏ vì tẩy
                trang nữa.
              </p>
            </div>
            <div>
              <h3 className="title-small">
                1. Tránh xa các thành phần gây kích ứng
              </h3>
              <p className="content-small">
                Đối với làn da nhạy cảm, điều quan trọng nhất chính là hãy luôn
                quan tâm đến thành phần trong sản phẩm tẩy trang để tránh bị
                kích ứng. Bạn sẽ khá bất ngờ khi nhìn thấy một số thành phần phổ
                biến như alcohol (cồn), paraben (chất bảo quản), mineral oil
                (dầu khoáng), fragrance (hương liệu),... sẽ có thể là nguyên
                nhân gây ra tình trạng kích ứng, mẩn đỏ cho làn da nhạy cảm. Vì
                thế, hãy kiểm tra thật kỹ bảng thành phần và loại ngay các sản
                phẩm chứa những chất trên để “đảm bảo an toàn” cho làn da nhạy
                cảm.
              </p>
              <img
                className="img-banner-makeup"
                src={bannermakeup.src}
                alt=""
              />
            </div>
            <div className="list-url">
              <div>
                <Link className="url" href="#">
                  <img className="img-makeup" src={makeup.src} alt="" />
                  <p>
                    Nước hoa Atelier Cologne Iris Rebelle Cologne Absolue Pure
                    Perfume
                  </p>
                  <img className="img-vector" src={vector.src} alt="" />
                </Link>
              </div>
              <div>
                <Link className="url" href="#">
                  <img className="img-makeup" src={makeup.src} alt="" />
                  <p>
                    Nước hoa Atelier Cologne Iris Rebelle Cologne Absolue Pure
                    Perfume
                  </p>
                  <img className="img-vector" src={vector.src} alt="" />
                </Link>
              </div>
              <div>
                <Link className="url" href="#">
                  <img className="img-makeup" src={makeup.src} alt="" />
                  <p>
                    Nước hoa Atelier Cologne Iris Rebelle Cologne Absolue Pure
                    Perfume
                  </p>
                  <img className="img-vector" src={vector.src} alt="" />
                </Link>
              </div>
            </div>
            <div>
              <h3 className="title-small">
                2. Tránh xa các thành phần gây kích ứng
              </h3>
              <p className="content-small">
                Đối với làn da nhạy cảm, điều quan trọng nhất chính là hãy luôn
                quan tâm đến thành phần trong sản phẩm tẩy trang để tránh bị
                kích ứng. Bạn sẽ khá bất ngờ khi nhìn thấy một số thành phần phổ
                biến như alcohol (cồn), paraben (chất bảo quản), mineral oil
                (dầu khoáng), fragrance (hương liệu),... sẽ có thể là nguyên
                nhân gây ra tình trạng kích ứng, mẩn đỏ cho làn da nhạy cảm. Vì
                thế, hãy kiểm tra thật kỹ bảng thành phần và loại ngay các sản
                phẩm chứa những chất trên để “đảm bảo an toàn” cho làn da nhạy
                cảm.
              </p>
              <img
                className="img-banner-makeup"
                src={bannermakeup.src}
                alt=""
              />
            </div>
            <p className="tag">TAG</p>
            <div className="list-tag">
              <div className="option-tag">Dưỡng trắng</div>
              <div className="option-tag">Dưỡng trắng</div>
              <div className="option-tag">Dưỡng trắng</div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
