import Head from "next/head";
import Pagination from "../../components/Pagination/Pagination";
import Image from "next/image";
import Link from "next/link";
import { isArray } from "../../utils";
import { useRouter } from "next/router";
import styles from '../../styles/magazine.module.scss'
// import  '../styles/magazine.scss'
import bigbanner from "../../public/group 3065.png";
import smallbanner from "../../public/content.png";
import Header from "../../components/Header/Header";
import Carousel from "../../components/Carousel/Carousel";
import Layout from "../../components/Layout/Layout";
import ProductPanel from "../../components/ProductPanel/ProductPanel";
import Footer from "../../components/Footer/Footer";
import { width } from "@mui/system";
import classNames from "classnames";
const adsArray = [
  {
    img: "",
    link: "#",
    title: "BEAUTY",
    content:
      "Daydreaming in Japan: a colouring book inspired by the streets of Nippon",
  },
  {
    img: "",
    link: "#",
    title: "BEAUTY",
    content:
      "Daydreaming in Japan: a colouring book inspired by the streets of Nippon",
  },
];

const renderContent = () => {
  return (
    <div className={styles.small_url}>
      <Link className={styles.url} href="#">
        <img src={smallbanner.src} alt="" />
        <p className={classNames("title-small start")}>BEAUTY</p>
        <h4 className="content-small start">
          Daydreaming in Japan: a colouring book inspired by the streets of
          Nippon
        </h4>
      </Link>
    </div>
  );
};

export default function magazine() {
  return (
    <>
      <Head>
        <title>Magazine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="magazine">
        <Header />
        <Layout>
          <div>
            <Image
              src={require("../../public/group 3065.png")}
              alt=""
              className={styles.img_banner}
            />
            <h1 className={styles.title_1}>Đẹp xinh lung linh, Tự tin khoe sắc</h1>
            <div className={styles.group_banner_small}>
              <Image
                src={require("../../public/content.png")}
                alt=""
                className={styles.small_banner}
              />
              <div className={styles.group_content}>
                <p className={styles.title_small}>BEAUTY</p>
                <h2 className={styles.content_small}>
                  Daydreaming in Japan: a colouring book inspired by the streets
                  of Nippon
                </h2>
              </div>
            </div>
          </div>
          <div className={styles.section_main}>
            <div className={styles.section01}>
              {isArray(adsArray) &&
                adsArray.map((item: any, index: number) => (
                  <Link className={styles.url} key={index} href={item.link}>
                    <Image
                      src={item.img || require("../../public/content.png")}
                      alt=""
                      className={styles.img}
                    />
                    <p className="title-small start">{item.title}</p>
                    <h4 className="content-small start">{item.content}</h4>
                  </Link>
                ))}
            </div>
            <div className={styles.line}></div>
            <div></div>
            <div className={styles.section02}>
              <p className={styles.title}>CHUYÊN MỤC</p>
              <div className={styles.list_option}>
                <div className={styles.option}>Beauty</div>
                <div className={styles.option}>Bài viết hot nhất</div>
                <div className={styles.option}>Chăm sóc da mặt</div>
              </div>
              <div className={styles.list_url}>
                {renderContent()}
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
