import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { isArray } from '../utils'

import styles from '../styles/Homepage.module.scss'

import Header from '../components/Header/Header'
import Carousel from '../components/Carousel/Carousel'
import Layout from '../components/Layout/Layout'
import ProductPanel from '../components/ProductPanel/ProductPanel'
import Footer from '../components/Footer/Footer'
const TicketArrays = [
    {
      img: require("../public/Frame 3277.png"),
      link: "#",
      title:"Sale10",
      content: "Tặng ngay 1000k cho 200 đơn hàng đầu tiên,đơn hàng đầu.",
    },
    {
        img: require("../public/Frame 3277.png"),
        link: "#",
        title:"Sale10",
        content: "Tặng ngay 1000k cho 200 đơn hàng đầu tiên,đơn hàng đầu.",
    },
    {
        img: require("../public/Frame 3277.png"),
        link: "#",
        title:"Sale10",
        content: "Tặng ngay 1000k cho 200 đơn hàng đầu tiên,đơn hàng đầu.",
    },
    {
        img: require("../public/Frame 3277.png"),
        link: "#",
        title:"Sale10",
        content: "Tặng ngay 1000k cho 200 đơn hàng đầu tiên,đơn hàng đầu.",
    },
  ]

export default function homepage() {
    return (
      <>
        <Head>
          <title>Lixi Box</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          <Header />
          <Layout>
            <div className={styles.homepage}>
                <Image
                    src={require("../public/banner-homepage.png")}
                    alt=""
                    className={styles.banner_homepage}
                />
                <div className={styles.list_ticket}>
                    {isArray(TicketArrays) && TicketArrays.map((item: any, index: number) => (
                        <div className={styles.ticket}>
                          <div className={styles.background}>
                            <Image
                                  src={require("../public/group 3343.png")}
                                  alt=""
                                  className={styles.ticket_img}
                              />
                          </div>
                            <div className={styles.left_ticket}>
                                <div className={styles.info_ticket}>
                                  <div className={styles.title}>{item.title}</div>
                                  <Image className={styles.client}
                                  src={item.img}              
                                  alt=""
                                  />
                                </div>
                                <div className={styles.content}>{item.content}</div>
                            </div>
                            <div>
                                <Link className={styles.url} key={index} href={item.link}>
                                Lưu mã
                                </Link>
                            </div>
                        </div>
                    ))}
                </div>
                <div>
                </div>          
            </div>
          </Layout>
        </main>
      </>
    );
  }