import Head from 'next/head'
import Pagination from '../components/Pagination/Pagination'
import Image from 'next/image'
import Link from 'next/link'
import { isArray } from '../utils'
import { useRouter } from 'next/router'
// import  '../styles/magazine.scss'
import bigbanner from '../public/group 3065.png' 
import smallbanner from '../public/content.png' 
import Header from '../components/Header/Header'
import Carousel from '../components/Carousel/Carousel'
import Layout from '../components/Layout/Layout'
import ProductPanel from '../components/ProductPanel/ProductPanel'
import Footer from '../components/Footer/Footer'
import { width } from '@mui/system'
const adsArray = [
    {
      img: "",
      link:"#",
      title:"BEAUTY",
      content:"Daydreaming in Japan: a colouring book inspired by the streets of Nippon",
    },
    {
        img: "",
        link:"#",
        title:"BEAUTY",
        content:"Daydreaming in Japan: a colouring book inspired by the streets of Nippon",
      },
  ]

// export default function AdminUser{
//     const router = useRouter;

// }
export default function magazine(){
    return(
        <>
            <Head>
                <title>Magazine</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Header/>
                <Layout>
                <div>
                    <img className='img-banner' src={bigbanner.src} alt="" />
                    <h1 className='title-1'>Đẹp xinh lung linh, Tự tin khoe sắc</h1>
                    <div className='group-banner-small'>
                        <img className='small-banner' src={smallbanner.src} alt="" />
                        <div className='group-content'>
                            <p className='title-small'>BEAUTY</p>
                            <h2 className='content-small'>Daydreaming in Japan: a colouring book inspired by the streets of Nippon</h2>
                        </div>
                    </div>
                </div>
                <div className='section-main'>
                    <div className='section01'>
                    {isArray(adsArray) && adsArray.map((item: any, index: number) => (
                        <Link className='url' key={index} href={item.link}>
                        <Image
                            src={item.img || require("../public/content.png")}              
                            alt=""
                            className='img'
                        />
                        <p className='title-small start'>{item.title}</p>
                        <h4 className='content-small start'>{item.content}</h4>
                        </Link>
                    ))}
                    </div>
                    <div className='line'></div>
                    <div></div>
                    <div className='section02'>
                        <p className='title'>CHUYÊN MỤC</p>
                        <div className='list-option'>
                            <div className='option'>
                            Beauty
                            </div>
                            <div className='option'>
                            Bài viết hot nhất
                            </div>
                            <div className='option'>
                            Chăm sóc da mặt
                            </div>
                        </div>
                        <div className='list-url'>
                            <div className='small-url'>
                            <Link className='url' href='#'>
                                <img src={smallbanner.src} alt="" />
                                <p className='title-small start'>BEAUTY</p>
                                <h4 className='content-small start'>Daydreaming in Japan: a colouring book inspired by the streets of Nippon</h4>
                            </Link>
                            </div>
                            <div className='small-url'>
                            <Link className='url' href='#'>
                                <img src={smallbanner.src} alt="" />
                                <p className='title-small start'>BEAUTY</p>
                                <h4 className='content-small start'>Daydreaming in Japan: a colouring book inspired by the streets of Nippon</h4>
                            </Link>
                            </div>
                            <div className='small-url'>
                            <Link className='url' href='#'>
                                <img src={smallbanner.src} alt="" />
                                <p className='title-small start'>BEAUTY</p>
                                <h4 className='content-small start'>Daydreaming in Japan: a colouring book inspired by the streets of Nippon</h4>
                            </Link>
                            </div>
                            <div className='small-url'>
                            <Link className='url' href='#'>
                                <img src={smallbanner.src} alt="" />
                                <p className='title-small start'>BEAUTY</p>
                                <h4 className='content-small start'>Daydreaming in Japan: a colouring book inspired by the streets of Nippon</h4>
                            </Link>
                            </div>
                            <div className='small-url'>
                            <Link className='url' href='#'>
                                <img src={smallbanner.src} alt="" />
                                <p className='title-small start'>BEAUTY</p>
                                <h4 className='content-small start'>Daydreaming in Japan: a colouring book inspired by the streets of Nippon</h4>
                            </Link>
                            </div>
                            <div className='small-url'>
                            <Link className='url' href='#'>
                                <img src={smallbanner.src} alt="" />
                                <p className='title-small start'>BEAUTY</p>
                                <h4 className='content-small start'>Daydreaming in Japan: a colouring book inspired by the streets of Nippon</h4>
                            </Link>
                            </div>
                            <div className='small-url'>
                            <Link className='url' href='#'>
                                <img src={smallbanner.src} alt="" />
                                <p className='title-small start'>BEAUTY</p>
                                <h4 className='content-small start'>Daydreaming in Japan: a colouring book inspired by the streets of Nippon</h4>
                            </Link>
                            </div>
                            <div className='small-url'>
                            <Link className='url' href='#'>
                                <img src={smallbanner.src} alt="" />
                                <p className='title-small start'>BEAUTY</p>
                                <h4 className='content-small start'>Daydreaming in Japan: a colouring book inspired by the streets of Nippon</h4>
                            </Link>
                            </div>
                            <div className='small-url'>
                            <Link className='url' href='#'>
                                <img src={smallbanner.src} alt="" />
                                <p className='title-small start'>BEAUTY</p>
                                <h4 className='content-small start'>Daydreaming in Japan: a colouring book inspired by the streets of Nippon</h4>
                            </Link>
                            </div>
                        </div>
                    </div>
                </div>
                </Layout>
            </main>
        </>
    )
}