import Head from "next/head";
import styles from '../styles/nontification.module.scss'
import Pagination from "../components/Pagination/Pagination";
import Image from "next/image";
import Link from "next/link";
import { isArray } from "../utils";
import { useRouter } from "next/router";
import Header from "../components/Header/Header";
import Carousel from "../components/Carousel/Carousel";
import Layout from "../components/Layout/Layout";
import ProductPanel from "../components/ProductPanel/ProductPanel";
import Footer from "../components/Footer/Footer";
import { width } from "@mui/system";
import classNames from "classnames";
const block1Array = [
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Bài viết của tôi",
  },
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Chỉnh sửa thông tin",
  },
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Thông tin giao hàng",
  },
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Đổi mật khẩu",
  }
]
const block2Array = [
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Sản phẩm đã xem",
  },
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Sản phẩm yêu thích",
  },
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Sản phẩm đánh giá",
  },
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Chờ hàng về",
  }
]
const block3Array = [
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Chương trình Cheripoints",
  },
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Lịch sử Cheripoint",
  },
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Giới thiệu bạn bè",
  },
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Thông tin CheriCT",
  },
  {
    img: require("../public/eye.png"),
    link: "#",
    content: "Gửi yêu cầu hỗ trợ",
  }
]
const choices = Array(8).fill({
  text: "Đơn hàng #202453119 đã sẵn sàng để giao đến quý khách. Chúng tôi vừa bàn giao đơn hàng của quý khách đến đối tác vận chuyển Cherict Team. Đơn hàng sẽ được",

})
const renderChoices = function (choices) {
  return (
      choices.map((choice,index) => (
        <div>
                <Link  href="#" className={styles.product}>
                  <div className={styles.product_info}>
                    <Image className={styles.img} src={require("../public/rectangle 559.png")} alt="" width={52} height={52}/>
                    <div>
                      <p className={styles.product_name}>Chia sẻ nhận xét về sản phẩm</p>
                      <p className={styles.product_content}>{choice.text}</p>
                      <p className={styles.product_date}>14/01/2021</p>
                    </div>
                  </div>
                  <div className={styles.product_more}>
                    <p className={styles.product_all}>Xem chi tiết</p>
                    <p className={styles.product_del}>Xoá</p>
                  </div>
                </Link>
              </div>
          )
      )
  );
}
export default function nontification() {
    return (
      <>
        <Head>
          <title>Nontification</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="nontification">
          <Header />
          <Layout>
            <div className={styles.layout}>
              <div className={styles.section_left}>
                <div className={styles.section_1}>
                    <div className={styles.avatar_border}>
                        <Image className={styles.avatar} src={require("../public/content.png")} alt="" width={90} height={90} />
                    </div>
                    <div className={styles.member}>
                      MEMBER
                    </div>
                    <div className={styles.name}>Thảo Nguyên</div>
                    <div className={styles.block_number}>
                      <div className={styles.block_number_small}>
                        <h3 className={styles.number}>152</h3>
                        <p className={styles.name_number}>coin</p>
                      </div>
                      <div className={styles.line}></div>
                      <div className={styles.block_number_small}>
                        <h3 className={styles.number}>0</h3>
                        <p className={styles.name_number}>coin</p>
                      </div>
                    </div>
                </div>
                <div className={styles.section_2}>
                  <Image className={styles.img} src={require("../public/eye.png")} alt="" width={16} height={16} />
                  <p className={styles.text}>Đơn mua hàng</p>
                </div>
                <div className={styles.section_3}>
                  <div className={styles.title_3}>
                    <div className={styles.title_small_3}>
                      <Image src={require("../public/eye.png")} alt="" width={16} height={16} />
                      <p className={styles.text}>Tài khoản</p>
                    </div>
                    <Image src={require("../public/Vector-yellow.png")} alt="" width={12} height={6} />
                  </div>
                  {isArray(block1Array) && block1Array.map((item: any, index: number) => (
                    <Link className={styles.url} key={index} href={item.link}>
                      <Image className={styles.img}
                        src={item.img}              
                        alt=""
                      />
                      <div className={styles.content}>{item.content}</div>
                    </Link>
                  ))}
                </div>
                <div className={styles.section_3}>
                  <div className={styles.title_3}>
                    <div className={styles.title_small_3}>
                      <Image src={require("../public/eye.png")} alt="" width={16} height={16} />
                      <p className={styles.text}>Sản phẩm</p>
                    </div>
                    <Image src={require("../public/Vector-yellow.png")} alt="" width={12} height={6} />
                  </div>
                  {isArray(block2Array) && block2Array.map((item: any, index: number) => (
                    <Link className={styles.url} key={index} href={item.link}>
                      <Image className={styles.img}
                        src={item.img}              
                        alt=""
                      />
                      <div className={styles.content}>{item.content}</div>
                    </Link>
                  ))}
                </div>
                <div className={styles.section_3}>
                  <div className={styles.title_3}>
                    <div className={styles.title_small_3}>
                      <Image src={require("../public/eye.png")} alt="" width={16} height={16} />
                      <p className={styles.text}>Thông tin tài khoản</p>
                    </div>
                    <Image src={require("../public/Vector-yellow.png")} alt="" width={12} height={6} />
                  </div>
                  {isArray(block3Array) && block3Array.map((item: any, index: number) => (
                    <Link className={styles.url} key={index} href={item.link}>
                      <Image className={styles.img}
                        src={item.img}              
                        alt=""
                      />
                      <div className={styles.content}>{item.content}</div>
                    </Link>
                  ))}
                </div>
              </div>
              <div className={styles.section_right}>
                <h2 className={styles.big_title}>Thông báo của tôi</h2>
                <div className={styles.small_title}>
                  <div className={styles.options}>
                    <h4 className={styles.title_show}>Tất cả</h4>
                    <h4 className={styles.title}>Đơn hàng</h4>
                    <h4 className={styles.title}>Khuyến mãi</h4>
                    <h4 className={styles.title}>Users</h4>
                  </div>
                  <p className={styles.read}>Đánh dấu đã đọc tất cả</p>
                </div>
                <div>
                  {renderChoices(choices)}
                </div>
              </div>
            </div>
          </Layout>
        </main>
      </>
    );
  }